import {StyleSheet} from 'react-native'

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
    paddingTop: 15,
  },
  icon: {
    width: 70,
    height: 70,
    left: 5,
    top: 5,
    position: 'absolute',
    // borderColor: 'black',
    // borderWidth: 1,
  },
  balenceView: {
    flex: 1,
    width: 200,
    bottom: 10,
    alignItems: "center",
    justifyContent: 'center',
    // borderColor: 'black',
    // borderWidth: 1,
  },
  PosText:{
    fontSize: 50,
    fontWeight: "bold",
    alignSelf:"center",
    color: 'green',
    // borderColor: 'black',
    // borderWidth: 1,
  },
  NegText:{
    fontSize: 50,
    fontWeight: "bold",
    alignSelf:"center",
    color: 'red',
    // borderColor: 'black',
    // borderWidth: 1,
  },
  inputView: {
    flex: 1,
    width: 400,
    height: 600,
    bottom: 30,
    justifyContent: 'center',
    // borderColor: 'red',
    // borderWidth: 1,
  },
  input: {
    backgroundColor: 'silver',
    borderColor: 'black',
    borderWidth: 1,
    height: 40,
    width: 300,
    padding: 10,
    borderRadius: 4,
    alignSelf: "center",
  },
  buttonView: {
    width: 100,
    height: 100,
    bottom: 90,
    justifyContent: 'center',
    // borderColor: 'blue',
    // borderWidth: 1,
  },
  profile:{
    width: 60, 
    height: 60,
    alignSelf:"center",
  },
  payroll:{
    // borderColor: 'blue',
    // borderWidth: 1,
  }
});